HEADERS +=\
    $$PWD/TitleBar/mtitlewidget.h \
    $$PWD/TitleBar/SearchLineEdit.h \
    $$PWD/TitleBar/SearchMenu.h \
    $$PWD/TitleBar/TitleMenu.h \
    $$PWD/MidMainWidget/midMainWidget.h \
    $$PWD/BottomBar/mBottomWidget.h \
    $$PWD/BottomBar/mSlider.h \
    $$PWD/Base/basePushButton.h \
    $$PWD/Base/baseMenu.h \
    $$PWD/Base/baseTitleBar.h \
    $$PWD/MidRightWidget/MidRightWidget.h \
    $$PWD/MidMainWidget/stackWidget/midMainListWidget.h \
    $$PWD/MidMainWidget/stackWidget/midMainCloudWidget.h \
    $$PWD/MidMainWidget/stackWidget/midMainRadioWidget.h \
    $$PWD/MidMainWidget/stackWidget/midMainPhoneWidget.h \
    $$PWD/MidMainWidget/stackWidget/midMainLoadWidget.h \
    $$PWD/MidRightWidget/stackWidget/midRightLibraryWidget.h \
    $$PWD/MidRightWidget/stackWidget/midRightRadioWidget.h \
    $$PWD/MidRightWidget/stackWidget/midRightSongListWidget.h \
    $$PWD/MidRightWidget/stackWidget/midRightMVWidget.h \
    $$PWD/MidRightWidget/stackWidget/midRightLiveWidget.h \
    $$PWD/MidRightWidget/stackWidget/midrightLyricwidget.h \
    $$PWD/MidRightWidget/stackWidget/midRightKTVWidget.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListWidget.h \
    $$PWD/Base/baseWidget.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListButton.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListLineEdit.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListButtonMenu.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListLineEditMenu.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListListWidget.h \
    $$PWD/MidMainWidget/stackWidget/midPlayListListItem.h

SOURCES +=\
    $$PWD/TitleBar/mtitlewidget.cpp \
    $$PWD/TitleBar/SearchLineEdit.cpp \
    $$PWD/TitleBar/SearchMenu.cpp \
    $$PWD/TitleBar/TitleMenu.cpp \
    $$PWD/MidMainWidget/midMainWidget.cpp \
    $$PWD/BottomBar/mBottomWidget.cpp \
    $$PWD/BottomBar/mSlider.cpp \
    $$PWD/Base/basePushButton.cpp \
    $$PWD/Base/baseMenu.cpp \
    $$PWD/Base/baseTitleBar.cpp \
    $$PWD/MidRightWidget/MidRightWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midMainListWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midMainCloudWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midMainRadioWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midMainPhoneWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midMainLoadWidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midRightLibraryWidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midRightRadioWidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midRightSongListWidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midRightMVWidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midRightLiveWidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midrightLyricwidget.cpp \
    $$PWD/MidRightWidget/stackWidget/midRightKTVWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListWidget.cpp \
    $$PWD/Base/baseWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListButton.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListLineEdit.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListButtonMenu.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListLineEditMenu.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListListWidget.cpp \
    $$PWD/MidMainWidget/stackWidget/midPlayListListItem.cpp
